<a href="https://colab.research.google.com/github/JImaruf/Classification-/blob/main/Lab_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [ ]:
df = pd.read_csv("My Drive/DML/credit card.csv")

In [ ]:
df.isnull().sum()

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           2
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [ ]:
fill= df['AGE'].median()

In [ ]:
df.AGE = df.AGE.fillna(fill)


In [ ]:

X = df.drop(['default.payment.next.month'],axis=1)

In [ ]:
y= df['default.payment.next.month']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.30,random_state=1)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf=RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [ ]:
pred1 = rf.predict(X_test)
rf.score(X_test,y_test)
accuracy_score(y_test,pred1)


0.8135555555555556

In [ ]:
confusion_matrix(y_test,pred1)

array([[6624,  376],
       [1302,  698]])

In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)


GaussianNB()

In [ ]:
gnb.predict(X_test)

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
gnb.score(X_test,y_test)

0.37744444444444447

In [ ]:
from sklearn.naive_bayes import BernoulliNB

bnb = BernoulliNB()

In [ ]:
bnb.fit(X_train, y_train)

BernoulliNB()

In [ ]:
bnb.predict(X_test)

array([0, 1, 0, ..., 0, 0, 0])

In [ ]:
bnb.score(X_test,y_test)

0.771